### ISSUE TITLE
You're not @ noorderzon

### ISSUE THREAD

**Issue by Meneerdaniel** [JobLeonard/ProcessingCrashCourse#1]
But we are.  Please address this issue by calling meneer Daniel.

**Comment by JobLeonard** [comment]
Is dit Meneer Daniel Die Ooit Een Bananenpak Heeft Gedragen?

**Comment by Meneerdaniel** [comment]
Jo bel nog een keer.  Op een of andere manier in jouw nr weg.
Op 21 aug. 2015 22:18 schreef "Job van der Zwan" <notifications@github.com>:

**Comment by JobLeonard** [comment]
Tot gauw man! :)

**Comment by ismay** [comment]
@JobLeonard I too have been experiencing this issue!
